### ISSUE TITLE
help to build ARM64 version

### ISSUE THREAD

**Issue by ysmintor** [SuperNG6/docker-nginx#1]
Hi,
I'm learn from your docker nginx configure files, however, the compiled nginx version is not compatible with my ARM64 server. Although I've tried to modify 'platforms: linux/arm64', github action compiled result still get error result.

**Comment by SuperNG6** [comment]
The pagespeed module is not compatible with arm64, so needs to remove pagespeed module, then compile

**Comment by ysmintor** [comment]
Oh, I'm very glad that you had updated docker-nginx with arm64 version. I will try to follow with your newest packaged docker nginx version. Currently , my nginx configure file is copied from https://image.lvbibir.cn/blog/wordpress-blog.zip, I guessed there would need some modification in the inner nginx configure.

**Comment by SuperNG6** [comment]
Yes, you still need to adjust your nginx conf

**Comment by ysmintor** [comment]
Alright, I will try to change my nginx conf. Thanks for your help.
